name: Minerstorch
description: You can place torches with your pickage
main: me.kernelfreeze.minerstorch.MinersTorch
version: 1.0
api-version: 1.13
permissions:
    minerstorch.*:
        description: Gives access to all Miners torch features
        children:
            minerstorch.place: true
            minerstorch.unlimited: true
    minerstorch.place:
        description: Allows you to place torches from right clic pickages
        default: true
    minerstorch.unlimited:
        description: Allows you to place unlimited torches
        default: op
